const getData = () => {
    return [
        {
          "author": null,
          "title": "Viele Jahre gegen Magersucht gekämpft, nun steht sie im Halbfinal",
          "description": "Martina Trevisan hat sich erstmals in einen Major-Halbfinal gespielt. Früher kämpfte sie mit ihrer Gesundheit.",
          "url": "https://www.srf.ch/sport/tennis/grand-slam-turniere/trevisan-an-den-french-open-viele-jahre-gegen-magersucht-gekaempft-nun-steht-sie-im-halbfinal",
          "source": "SRF Sport",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "ch",
          "published_at": "2022-06-02T07:26:00+00:00"
        },
        {
          "author": "FOCUS Online",
          "title": "In Brasilien - Tottenham-Star nach Party überfallen - Polizist feuert 20 Schüsse ab",
          "description": "Emerson Royal ist in seinem Heimatland Brasilien Opfer eines bewaffneten Überfalls geworden. Dem Rechtsverteidiger von Tottenham Hotspur war ein Polizist, der zufällig in der Nähe war, zu Hilfe geeilt und habe zahlreiche Schüsse abgegeben, heißt es.",
          "url": "https://www.focus.de/sport/fussball/premierleague/20-schuesse-wurden-abgegeben-emerson-royal-von-raeubern-in-brasilianischem-club-ueberfallen-und-dieb-erschossen_id_107942431.html",
          "source": "Focus",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-03T14:29:25+00:00"
        },
        {
          "author": "Abendzeitung",
          "title": "Christoph Schickhardt - Lewandowski auf Tribüne setzen: Star-Anwalt hält extreme Bayern-Maßnahme für möglich",
          "description": "Robert Lewandowski will den FC Bayern in diesem Sommer verlassen, dabei hat der Stürmer aber noch ein Jahr Vertrag in München. Der Klub sitzt allerdings am längeren Hebel, sagt Christoph Schickhardt. Der Star-Anwalt erklärt, warum - und welche Sanktionsmöglichkeiten es gibt.",
          "url": "https://www.focus.de/sport/fussball/christoph-schickhardt-lewandowski-auf-tribuene-setzen-anwalt-haelt-extreme-bayern-massnahme-fuer-moeglich_id_107940078.html",
          "source": "Focus",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-04T10:06:44+00:00"
        },
        {
          "author": "sportschau.de",
          "title": "DFB-Team: Einstimmung auf vier Spiele in elf Tagen",
          "description": "Das DFB-Team unter Trainer Hansi Flick bestreitet in Bologna ihr erstes Nations-League-Spiel gegen Italien. Es ist der Auftakt einer Länderspielserie.",
          "url": "https://www.sportschau.de/fussball/nationsleague/video-dfb-team-einstimmung-auf-vier-spiele-in-elf-tagen-100.html",
          "source": "Sportschau ARD",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-04T10:52:48+00:00"
        },
        {
          "author": null,
          "title": "Ungarische Zuschauer sorgen bei «Geisterspiel» für Kopfschütteln",
          "description": "Beim 0:1 von England in Budapest im Rahmen der Nations League gab es erneut skandalöse Begleitumstände.",
          "url": "https://www.srf.ch/sport/fussball/nations-league/buhrufe-bei-englands-kniefall-ungarische-zuschauer-sorgen-bei-geisterspiel-fuer-kopfschuetteln",
          "source": "SRF Sport",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "ch",
          "published_at": "2022-06-05T10:42:00+00:00"
        },
        {
          "author": "sportschau.de",
          "title": "Mannheimer HC gegen Harvestehuder THC - das komplette Spiel",
          "description": "Final Four der Hockey-Männer: das Spiel um Platz drei zwischen dem Mannheimer HC und dem Harvestehuder THC in voller Länge.",
          "url": "https://www.sportschau.de/hockey/video-mannheimer-hc-gegen-harvestehuder-thc---das-komplette-spiel-100.html",
          "source": "Sportschau ARD",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-05T11:51:25+00:00"
        },
        {
          "author": "Stefan Döring",
          "title": "Kein Karriere-Ende: Paris-Champion Nadal will trotz Fußproblemen weiter „kämpfen“",
          "description": "Anders als befürchtet ist Rafael Nadal am Sonntag nach seinem 14. Titel bei den French Open nicht zurückgetreten. Trotz gesundheitlicher Probleme will er weiterspielen.",
          "url": "https://rp-online.de/sport/tennis/french-open/french-open-rafael-nadal-will-trotz-fussproblemen-weiter-um-karriere-kaempfen_aid-70887223",
          "source": "RP Onlione Sport",
          "image": "https://rp-online.de/imgs/32/1/3/3/0/8/1/8/9/7/tok_b00b8ca31bb8fe99d5e05c44438bfdef/w950_h950_x1500_y1000_AP_32A98A0085A96DB1-7aad2a8eacc3e977.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-05T16:13:00+00:00"
        },
        {
          "author": "Stefan Döring",
          "title": "Nations-League-Spiel in München: Hier können Sie Deutschland gegen England live im Free-TV sehen",
          "description": "In dieser Saison der Nations League wird es etwas komplizierter für den TV-Zuschauer. Die Spiele der DFB-Elf laufen nicht mehr alle nur bei RTL. Auch das ZDF wird in den kommenden Tagen übertragen.",
          "url": "https://rp-online.de/sport/fussball/nationalelf/nations-league-2022-2023-dfb-team-live-im-free-tv-so-sehen-sie-das-spiel-gegen-england_aid-70843461",
          "source": "RP Onlione Sport",
          "image": "https://rp-online.de/imgs/32/1/3/3/0/3/5/8/3/7/tok_ae0fa7b9332caf283e19cfb05d4fe4b1/w950_h950_x1273_y556_DPA_bfunk_dpa_5FA98C003534568F-b35f7a44ea8e128a.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-07T10:57:00+00:00"
        },
        {
          "author": null,
          "title": "Kadetten Schaffhausen sind Schweizer Meister",
          "description": "Die Kadetten Schaffhausen gewinnen zuhause auch Spiel 3 des Playoff-Finals gegen Pfadi Winterthur und holen den Titel.",
          "url": "https://www.srf.ch/sport/mehr-sport/handball/3-0-im-final-gegen-pfadi-kadetten-schaffhausen-sind-schweizer-meister",
          "source": "SRF Sport",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "ch",
          "published_at": "2022-06-07T17:46:00+00:00"
        },
        {
          "author": null,
          "title": "Nach dem England-Spiel: DFB-Auswahl „noch nicht auf dem Höhepunkt“ – aber es geht voran",
          "description": "Nichts Halbes und nichts Ganzes. Das 1:1 gegen England ist noch nicht der große Schritt der Nationalmannschaft Richtung WM-Form. Aber die Auswahl von Hansi Flick zeigt sich in München stark verbessert. Es gibt einige Gewinner.",
          "url": "https://rp-online.de/sport/fussball/nationalelf/fussball-dfb-auswahl-ist-nach-dem-england-spiel-noch-nicht-auf-dem-hoehepunkt_aid-71014941",
          "source": "RP Onlione Fußball",
          "image": "https://rp-online.de/imgs/32/1/3/3/2/9/7/3/7/7/tok_c2ab36880c861e4c3040070de53eff1a/w950_h950_x1300_y866_DPA_bfunk_dpa_5FA98E0091ADC163-8da751db71af0c7c.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-08T07:46:00+00:00"
        },
        {
          "author": null,
          "title": "Der neue FCZ-Trainer heisst Franco Foda",
          "description": "Schweizer Meister FCZ ist auf der Suche nach einem Nachfolger für André Breitenreiter fündig geworden.",
          "url": "https://www.srf.ch/sport/fussball/super-league/nachfolger-von-breitenreiter-der-neue-fcz-trainer-heisst-franco-foda",
          "source": "SRF Sport",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "ch",
          "published_at": "2022-06-08T13:53:00+00:00"
        },
        {
          "author": "Thomas Schulze",
          "title": "Keine Auflagen vom Verband: Uerdingen kann in der Oberliga in der Grotenburg spielen",
          "description": "Am 19. Juni ist Trainingsauftakt, am 7. August beginnt die Meisterschaft. Der KFC Uerdingen will erstmals seit vier Jahren seine Heimspiele wieder im Stadion Grotenburg austragen. In der Fußball-Oberliga scheint das möglich.",
          "url": "https://rp-online.de/sport/fussball/kfc-uerdingen/fussball-kfc-uerdingen-startet-erstmals-seit-vier-jahren-in-der-grotenburg_aid-71035941",
          "source": "RP Onlione Fußball",
          "image": "https://rp-online.de/imgs/32/1/3/3/3/4/5/5/8/1/tok_502199192a1683ed0f170196785f74cc/w950_h901_x599_y450_20220507_OK_KFCS04_0570-fcc3947082c7ecdc.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-08T14:36:00+00:00"
        },
        {
          "author": "Susanne Ruckert",
          "title": "Zach Magwood kommt aus Innsbruck: Torjäger Nikita Shatsky kehrt zu den Pinguinen zurück",
          "description": "Ein Jahr war er weg, jetzt ist Nikita Shatsky wieder da. Zudem haben die Pinguine Stürmer Zach Magwood verpflichtet, der zuletzt in Innsbruck gespeilt hat. Sprtdirektor Sergey Saveljev ist von den Neuen überzeugt. Damit sind vier der sechs Ausländerlizenzen vergeben.",
          "url": "https://rp-online.de/sport/eishockey/kev/eishockey-del2-krefeld-pinguine-haben-vier-der-sechs-kontingentspielerlizenzen-vergeben_aid-71098867",
          "source": "RP Onlione Sport",
          "image": "https://rp-online.de/imgs/32/1/3/3/4/6/4/5/8/3/tok_dbeb8c84857fd59cf5969430d7b61166/w950_h950_x1771_y1181_RP_Krefeld_Pinguine-Grizzlys_Wolfsburg027-f926b5cc82d42948.JPG",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-09T15:08:00+00:00"
        },
        {
          "author": null,
          "title": "Das Stadion-Desaster: Wo soll Österreich zukünftig spielen? [premium]",
          "description": "Stromausfall, Loch im Rasen: Die Vorkommnisse der vergangenen Tage haben die Stadion-Debatte neu entfacht. Wirtschaftliche Interessen spielen eine große Rolle, aber: Muss es immer Wien sein?",
          "url": "https://www.diepresse.com/6150689/OeFBTeam_Das-StadionDesaster_Wo-soll-Oesterreich-zukuenftig-spielen?from=rss",
          "source": "DiePresse.com",
          "image": "https://media.diepresse.com/images/uploads_500/a/2/1/6150689/0B9436C7-05E0-490A-913C-58801AE49EFD_v0_l.jpg",
          "category": "sports",
          "language": "de",
          "country": "at",
          "published_at": "2022-06-09T15:09:00+00:00"
        },
        {
          "author": "Tim Kronner, Phillip Oldenburg, Aaron Knopp, Stefan Döring, Maximilian Lonn",
          "title": "French Open: Cilic bezwingtr Rublew auf dem Weg ins Halbfinale",
          "description": "Die French Open sind das zweite Grand-Slam-Turnier des Jahres. Bis zum 22. Juni wird in Paris um den Titel gespielt. Wem gelingt der Triumph beim Sandplatz-Turnier? In unserem Telegramm verpassen Sie nichts.",
          "url": "https://rp-online.de/sport/tennis/french-open/french-open-2022-cilic-bezwingtr-rublew-auf-dem-weg-ins-halbfinale_aid-53620155",
          "source": "RP Onlione Sport",
          "image": "https://rp-online.de/imgs/32/9/1/4/6/7/3/3/5/tok_6e65be81cb711ea4ed44df7763cba089/w950_h950_x1936_y1296_AFP_fAFP_32BP8XQ-401a1bf9fb710cb3.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-01T18:56:00+00:00"
        },
        {
          "author": "Hannah Gobrecht",
          "title": "Auftakt der Nations League: Schweizer Borussia-Profis mit entscheidenden Fehlern gegen Tschechien",
          "description": "Borussias Schweizer Nationalspieler sind mit einer Niederlage in die Nations League gestartet. Gegen Tschechien herrschte bei beiden Gegentoren im Strafraum von Torhüter Yann Sommer Chaos. Manu Koné hingegen darf sich über sein Debüt in der U21 Frankreichs freuen.",
          "url": "https://rp-online.de/sport/fussball/borussia/gladbach-manu-kone-feiert-debuet-in-frankreichs-u21-team_aid-70781049",
          "source": "RP Onlione Fußball",
          "image": "https://rp-online.de/imgs/32/1/3/2/9/2/0/6/6/5/tok_84eefff2c811d188496e90c65d90de56/w950_h950_x1403_y670_AP_32A98400084F83A3-f884284cc8c00c9e.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-03T07:16:09+00:00"
        },
        {
          "author": "Aaron Knopp",
          "title": "Zurück in die Zukunft: Was dafür spricht, es noch mal mit dem Ex-Trainer zu versuchen",
          "description": "Viel sprach für eine zweite Amtszeit von Lucien Favre in Mönchengladbach, Edin Terzic war nie weg, übernimmt nun aber ein zweites Mal das Traineramt beim BVB. Können solche Rückholaktionen überhaupt gelingen? Für beide Seiten spricht zumindest einiges dafür, es noch mal mit dem Ex zu versuchen.",
          "url": "https://rp-online.de/sport/fussball/bundesliga/terzic-favre-bueskens-warum-viele-bundesliga-trainer-eine-zweite-chance-bekommen_aid-70611671",
          "source": "RP Onlione Sport",
          "image": "https://rp-online.de/imgs/32/1/3/2/6/0/2/4/4/3/tok_9e38cdbbc17c4683b7ae2159f1a299e8/w950_h950_x1148_y602_DPA_bfunk_dpa_5FA97000EB33D1BB-52486bb6b6670d80.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-03T15:11:00+00:00"
        },
        {
          "author": "FOCUS Online",
          "title": "Geschäftsführer wittert Chance - Watzke über Bayern: irgendwann kommt es zum Einsturz“",
          "description": "Serge Gnabry hat das Vertrags-Angebot des FC Bayern Münchens bisher nicht angenommen. In einer Pressekonferenz spricht Joshua Kimmich offen über seinen „besten Freund“.",
          "url": "https://www.focus.de/sport/fussball/bundesliga1/sandro-schwarz-emotional-watzke-ueber-bayern-irgendwann-kommt-es-zum-einsturz_id_107942640.html",
          "source": "Focus",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-03T15:17:24+00:00"
        },
        {
          "author": "sportschau.de",
          "title": "Tor 3 - Marian Riedinger",
          "description": "Marian Riedinger trifft im Spiel der Oberliga Baden-Württemberg gegen den FV Lörrach-Brombach zum 3:0.",
          "url": "https://www.sportschau.de/tor-des-monats/video-tor----marian-riedinger-100.html",
          "source": "Sportschau ARD",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-03T20:12:28+00:00"
        },
        {
          "author": "sportschau.de",
          "title": "Tor 1 - Rodrigo Zalazar",
          "description": "Rodrigo Zalazar trifft für den FC Schalke 04 im Spiel der 2. Bundesliga gegen den 1. FC Nürnberg zum 1:0.",
          "url": "https://www.sportschau.de/tor-des-monats/video-tor----rodrigo-zalazar-100.html",
          "source": "Sportschau ARD",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-03T20:12:26+00:00"
        },
        {
          "author": "sportschau.de",
          "title": "Hockey-Final-Four: Rot-Weiss Köln gegen den Harvestehuder THC",
          "description": "Im Final Four 2022 in Bonn trafen Rot-Weiss Köln und der Harvestehuder THC aufeinander",
          "url": "https://www.sportschau.de/hockey/video-hockey-final-four-rot-weiss-koeln-gegen-den-harvestehuder-thc-100.html",
          "source": "Sportschau ARD",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-04T13:21:55+00:00"
        },
        {
          "author": "Stefan Döring",
          "title": "„Mein Herz zerschellte in tausend Teile“: Zverev teilt erste Diagnose mit – Mehrere Bänder gerissen",
          "description": "Es waren Bilder, die beim Anschauen wehtaten. Der Fuß von Alexander Zverev sah nach seinem Sturz im Paris-Halbfinale gegen Rafael Nadal überhaupt nicht gut aus. Wie lange der Olympiasieger ausfällt, ist noch unklar. Auf jeden Fall sind mehrere Bänder gerissen.",
          "url": "https://rp-online.de/sport/tennis/french-open/french-open-alexander-zverev-teilt-erste-diagnose-mit-mehrere-baender-gerissen_aid-70843155",
          "source": "RP Onlione Tennis",
          "image": "https://rp-online.de/imgs/32/1/3/3/0/3/5/5/1/3/tok_d51806700766cb934c5fc625641f68f6/w950_h950_x3642_y2039_AFP_fAFP_32BU86J-817ff762e90d8ac7.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-04T16:31:00+00:00"
        },
        {
          "author": "sportschau.de",
          "title": "Rangnicks Traumdebüt: Österreich feiert Auswärtserfolg in Kroatien",
          "description": "Zum Auftakt der Nations League hat Österreich einen klaren Sieg in Kroatien gefeiert. Beim Debüt des neuen Teamchefs Ralf Rangnick zeigte die ÖFB-Elf eine bemerkenswerte Leistung.",
          "url": "https://www.sportschau.de/fussball/nationsleague/video-rangnicks-traumdebuet-oesterreich-feiert-auswaertserfolg-in-kroatien-100.html",
          "source": "Sportschau ARD",
          "image": null,
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-04T16:26:17+00:00"
        },
        {
          "author": "Pascal Biedenweg, Gianni Costa, Bernd Jolitz",
          "title": "Senf drupp – die F95-Kolumne: Fortuna muss die Vorfreude jetzt ausnutzen",
          "description": "Ilja Ludenberg hat in vielen Funktionen für Fortuna gearbeitet: als langjähriger U23-Obmann, als Stadionsprecher und als Mitglied der Scoutingabteilung. In seiner Kolumne widmet er sich diesmal der Euphorie, die unter Daniel Thioune neu entfacht wurde. Und was der Verein damit anstellen muss.",
          "url": "https://rp-online.de/sport/fussball/fortuna/fortuna-duesseldorf-kolumne-senf-drupp-mit-ilja-ludenberg-frueher-u23-obmann-scout-und-stadionsprecher_aid-70786621",
          "source": "RP Onlione Fußball",
          "image": "https://rp-online.de/imgs/32/1/3/2/9/3/1/2/1/3/tok_7efe554110d5e9aad131b93e5be9f2ea/w950_h906_x728_y191_cw_Ludenberg_01-b77da40ae5a53da8.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-05T10:06:00+00:00"
        },
        {
          "author": null,
          "title": "Bester Torjäger: Lewandowski gewinnt Goldenen Schuh",
          "description": "Der polnische Stürmer Robert Lewandowski ist der beste Torjäger der Saison in Europa. Der Star des FC Bayern bekommt deshalb den Goldenen Schuh überreicht.",
          "url": "https://rp-online.de/sport/fussball/bayern-muenchen/bester-torjaeger-robert-lewandowski-gewinnt-goldenen-schuh_aid-70878245",
          "source": "RP Onlione Fußball",
          "image": "https://rp-online.de/imgs/32/1/3/3/0/7/1/8/7/9/tok_55281a8d33a95ac118742a45e3527043/w950_h950_x2203_y1469_AFP_fAFP_32BP9R8-033d545154279109.jpg",
          "category": "sports",
          "language": "de",
          "country": "de",
          "published_at": "2022-06-05T10:14:00+00:00"
        }
    ];
}

export default getData;